import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Nav } from "@/components/Nav";
import { ThemeProvider } from "@/components/theme-provider";
import { Flex, Box } from '@radix-ui/themes';
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = window.localStorage.getItem('theme');
                if (theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                } else if (theme === 'light') {
                  document.documentElement.classList.remove('dark');
                }
              })();
            `
          }}></script>
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <Flex direction="column" style={{ minHeight: '100vh' }}>
            <Nav />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </Flex>
        </ThemeProvider>
      </body>
    </html>
  );
}
